# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Healthcheck < Formula
  desc "Daily Mac CLI that scrapes investment funds from analizy.pl and posts a Telegram digest."
  homepage "https://github.com/lizarusi/investments-healthcheck"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lizarusi/investments-healthcheck/releases/download/v0.1.0/healthcheck-0.1.0-darwin-amd64.tar.gz"
    sha256 "e15eac7066582fe9482e169413f8086ad2b4ad6c59f601c7aebcb8f0c028f880"

    define_method(:install) do
      bin.install "healthcheck"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lizarusi/investments-healthcheck/releases/download/v0.1.0/healthcheck-0.1.0-darwin-arm64.tar.gz"
    sha256 "bc6ea65ad900764681c3c795dacad89d3d1b47f1ae739b2b964a7e642b0294e7"

    define_method(:install) do
      bin.install "healthcheck"
    end
  end

  test do
    assert_match "healthcheck", shell_output("#{bin}/healthcheck help")
  end
end
