# This file was generated by GoReleaser. DO NOT EDIT.
cask "fundpulse" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "3463f5def95991d7fd6c10d7ddbcb04ba69c0c28a0dbe83d7204c5d4769e0a42"
      url "https://github.com/lizarusi/fundpulse/releases/download/v#{version}/fundpulse-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "47a41013edc8711e12950ad351d640d1bffedffc6d313c1c5fd847e28cf38316"
      url "https://github.com/lizarusi/fundpulse/releases/download/v#{version}/fundpulse-#{version}-darwin-arm64.tar.gz"
    end
  end

  name "fundpulse"
  desc "Daily Mac CLI that scrapes investment funds from analizy.pl and posts a Telegram digest."
  homepage "https://github.com/lizarusi/fundpulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fundpulse"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/fundpulse"]
  end

  # No zap stanza required

end
