# This file was generated by GoReleaser. DO NOT EDIT.
cask "fundpulse" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "7b09a3b119ee174175c5595a2f8bfe36f022a52d06e29cb96391cfd62acd9efb"
      url "https://github.com/lizarusi/fundpulse/releases/download/v#{version}/fundpulse-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "7c8f9ea60600fb99d5fa9786c4295dab820cb0f55fd4c092b39a693bbddc81f5"
      url "https://github.com/lizarusi/fundpulse/releases/download/v#{version}/fundpulse-#{version}-darwin-arm64.tar.gz"
    end
  end

  name "fundpulse"
  desc "Daily Mac CLI that scrapes investment funds from analizy.pl and posts a Telegram digest."
  homepage "https://github.com/lizarusi/fundpulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fundpulse"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/fundpulse"]
  end

  # No zap stanza required

end
