# This file was generated by GoReleaser. DO NOT EDIT.
cask "healthcheck" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "91441336e017805cee1beb5854720df043f49bc8153a7531d7b1a10626e79ecf"
      url "https://github.com/lizarusi/investments-healthcheck/releases/download/v#{version}/healthcheck-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "04811d684a9e62375919dab997e9c5e421b94bd06408d60048c4270e3e6a5d9f"
      url "https://github.com/lizarusi/investments-healthcheck/releases/download/v#{version}/healthcheck-#{version}-darwin-arm64.tar.gz"
    end
  end

  name "healthcheck"
  desc "Daily Mac CLI that scrapes investment funds from analizy.pl and posts a Telegram digest."
  homepage "https://github.com/lizarusi/investments-healthcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "healthcheck"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/healthcheck"]
  end

  # No zap stanza required

end
