# This file was generated by GoReleaser. DO NOT EDIT.
cask "healthcheck" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "2019aa4a6b22816da1b4142ef2de94467460bebba515afdded55022b208d7e70"
      url "https://github.com/lizarusi/investments-healthcheck/releases/download/v#{version}/healthcheck-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "9629c4b52048fd493c853a8e903116508d9cc973e825d19164456fe5e989f43f"
      url "https://github.com/lizarusi/investments-healthcheck/releases/download/v#{version}/healthcheck-#{version}-darwin-arm64.tar.gz"
    end
  end

  name "healthcheck"
  desc "Daily Mac CLI that scrapes investment funds from analizy.pl and posts a Telegram digest."
  homepage "https://github.com/lizarusi/investments-healthcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "healthcheck"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/healthcheck"]
  end

  # No zap stanza required

end
