# This file was generated by GoReleaser. DO NOT EDIT.
cask "healthcheck" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "afde807a544ae0e5f94a03555acb67640274972a8a24fd1451f55b998fb8f186"
      url "https://github.com/lizarusi/investments-healthcheck/releases/download/v#{version}/healthcheck-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "29106af69a983b521685a9fdfdad509ed36f8fc594e1629001a34e329351f5c4"
      url "https://github.com/lizarusi/investments-healthcheck/releases/download/v#{version}/healthcheck-#{version}-darwin-arm64.tar.gz"
    end
  end

  name "healthcheck"
  desc "Daily Mac CLI that scrapes investment funds from analizy.pl and posts a Telegram digest."
  homepage "https://github.com/lizarusi/investments-healthcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "healthcheck"

  # No zap stanza required

end
